const frame = document.querySelector("#app");
const result = document.querySelector("#result");
const output = [];
function check(value, label) {
  output.push((value ? "PASS " : "FAIL ") + label);
  result.textContent = output.join("\n");
  if (!value) throw new Error(label);
}
document.querySelector("#run").onclick = async () => {
  const w = frame.contentWindow;
  const d = w.document;
  const s = w.eval("state");
  output.length = 0;
  try {
    check(typeof w.html2canvas === "function" && !!w.jspdf, "Local PDF dependencies");
    check(d.title==="Aren Academy TestMaker" && d.querySelector(".brand strong")?.textContent.trim()==="Aren Academy TestMaker" && d.querySelector(".brand-logo")?.getAttribute("src")==="./aren-logo-white.png", "Aren Academy branding and logo");
    const advancedButton=d.querySelector("#advancedToggleBtn");
    advancedButton.click();
    check(advancedButton.classList.contains("active") && advancedButton.getAttribute("aria-pressed")==="true" && !d.querySelector("#advancedPanel").classList.contains("hidden") && !d.querySelector(".mode-tab.active"),"Advanced settings has its own active state");
    d.querySelector('[data-exam-kind="sheet"]').click();
    check(s.examKind==="sheet" && d.querySelector('[data-exam-kind="sheet"]').classList.contains("active") && d.querySelector("#advancedPanel").classList.contains("hidden") && !d.querySelector("#basicPanel").classList.contains("hidden"),"Exam type exits advanced settings and restores its panel");
    advancedButton.click();
    d.querySelector('[data-exam-kind="trial"]').click();
    check(s.examKind==="trial" && d.querySelector('[data-exam-kind="trial"]').classList.contains("active"),"Trial mode can be selected after advanced settings");
    advancedButton.click();
    d.querySelector('[data-exam-kind="written"]').click();
    check(s.examKind==="written" && d.querySelector('[data-exam-kind="written"]').classList.contains("active"),"Written mode can be selected after advanced settings");
    const eraseCanvas=d.createElement("canvas");
    eraseCanvas.width=eraseCanvas.height=100;
    eraseCanvas.getContext("2d").fillRect(0,0,100,100);
    w.applyErasureStrokes(eraseCanvas,[{size:.2,points:[{x:.3,y:.5},{x:.7,y:.5}]}]);
    const erasedPixel=eraseCanvas.getContext("2d").getImageData(50,50,1,1).data;
    const keptPixel=eraseCanvas.getContext("2d").getImageData(5,5,1,1).data;
    check(erasedPixel[0]===255 && keptPixel[0]===0,"Eraser removes only the painted part of a crop");
    const blob = await (await fetch("./crop-fixture.png")).blob();
    await w.handleCropSourceFiles([new w.File([blob], "fixture.png", {type:"image/png"})]);
    check(s.pdfs.length === 1 && s.questions.length === 0, "Image opens in crop tool, not as an entire question");
    const canvas = d.querySelector("#pdfCanvas");
    let rect = canvas.getBoundingClientRect();
    const point = w.clientToCanvasPoint({clientX:rect.left+rect.width*.25,clientY:rect.top+rect.height*.3});
    check(Math.abs(point.x/canvas.width-.25)<.001 && Math.abs(point.y/canvas.height-.3)<.001, "Crop coordinate mapping at fitted width");
    s.selection = {startX:canvas.width*.05,startY:canvas.height*.09,endX:canvas.width*.75,endY:canvas.height*.3};
    s.eraseStrokes=[{size:.04,points:[{x:.1,y:.1},{x:.18,y:.1}]}];
    w.confirmPdfCrop();
    check(s.questions.length===1 && s.questions[0].erasureStrokes.length===1 && !s.questions[0].loaded && d.querySelectorAll(".question-card").length===0, "Pending crop keeps eraser edits and waits for Upload");
    const id = s.questions[0].id;
    w.editPdfCrop(id);
    s.selection.endX=canvas.width*.9;
    s.selectedAnswer="D";
    w.confirmPdfCrop();
    check(s.questions.length===1 && s.questions[0].id===id && s.questions[0].answer==="D" && Math.abs(s.questions[0].box.width-.85)<.01, "Editing crop preserves question ID and answer");
    w.markPdfQuestionsLoaded();
    check(d.querySelectorAll(".question-card").length===1, "Upload adds crop once");
    d.querySelector('.answer-row [data-answer="D"]').click();
    check(s.questions[0].answer==="", "Selected answer can be cleared");
    check(w.getQuestionNumberMap([{id:"one"},{id:"pending",loaded:false},{id:"two"}],false).get("two")==="2", "Pending crops do not create gaps in printed numbering");
    const originalWidth=d.querySelector(".question-card").offsetWidth;
    d.querySelector('[data-card-action="expand"]').click();
    check(d.querySelector(".question-card").offsetWidth===originalWidth && s.questions[0].expanded, "Expand changes paper only");
    s.cropZoom="2";
    await w.renderPdfPage();
    rect=canvas.getBoundingClientRect();
    const zoomPoint=w.clientToCanvasPoint({clientX:rect.left+rect.width*.6,clientY:rect.top+rect.height*.4});
    check(Math.abs(zoomPoint.x/canvas.width-.6)<.001,"Crop coordinate mapping after zoom");
    const pdfBlob=await(await fetch("./crop-fixture.pdf")).blob();
    await w.loadCropSources([new w.File([pdfBlob],"fixture.pdf",{type:"application/pdf"})]);
    check(s.pdfs.length===2 && canvas.width>0,"PDF source loads alongside image");
    await Promise.all([w.renderPdfPage(),w.renderPdfPage(),w.renderPdfPage()]);
    check(!s.cropRendering,"Concurrent page renders finish cleanly");
    w.closePdfModal();
    const source=s.questions[0].src;
    w.applyDraft({questions:["r1","r2","r3","r4"].map(id=>({id,kind:"image",src:source,loaded:true})),sections:[{id:"rs1",start:0,title:"Bir"},{id:"rs2",start:2,title:"Iki"}]});
    check(w.reorderQuestion("r4","r1",false) && s.questions.map(q=>q.id).join(",")==="r4,r1,r2,r3" && s.sections[1].start===3,"Question reorder updates order and section boundary");
    const questions=Array.from({length:16},(_,i)=>({id:"check-"+i,kind:"image",src:source,loaded:true,answer:i%2?"B":"",expanded:i===2,asDescription:i===0,customGap:i===3,bottomGap:i===3?5:0}));
    questions[5]={...questions[5],kind:"manual",html:'<p><b>Tabloyu inceleyiniz:</b></p><table><tr><td>12</td><td>24</td></tr></table><p>Toplam nedir?</p>'};
    w.applyDraft({questions,sections:[{id:"s1",start:0,title:"Turkce"},{id:"s2",start:8,title:"Matematik",resetNumbering:true,newPage:true}],settings:{globalGap:35,watermark:{enabled:true,type:"text",text:"KEY TEST",opacity:20,size:80,angle:45,color:"#174a7c"}},fields:{testTitle:"Turkce denemesi",includeAnswerKey:true,includeOptic:true,groupName:"2"}});
    check(w.getQuestionGap(s.questions[3])===5 && w.getQuestionGap(s.questions[4])===35,"Per-question spacing overrides global gap");
    await w.openDocumentPreview();
    let pages=[...d.querySelectorAll(".paper-page")];
    check(pages.length>1,"Questions paginate across multiple A4 sheets");
    check(Math.abs(pages[0].offsetWidth/pages[0].offsetHeight-210/297)<.002,"True A4 proportions");
    check(d.querySelectorAll(".final-question").length===16,"All questions and descriptions appear exactly once");
    const customGap=parseFloat(w.getComputedStyle(d.querySelector('[data-question-id="check-3"]')).marginBottom);
    const globalGap=parseFloat(w.getComputedStyle(d.querySelector('[data-question-id="check-4"]')).marginBottom);
    check(Math.abs(customGap-5*96/25.4)<.1 && Math.abs(globalGap-35*96/25.4)<.1,"Printed spacing is exactly 5 mm and 35 mm");
    check(!d.querySelector('[data-question-id="check-0"] .printed-question-number'),"Description has no question number");
    check(d.querySelector('[data-question-id="check-2"]').offsetWidth>d.querySelector('[data-question-id="check-1"]').offsetWidth*1.8,"Expanded question spans both columns");
    const normalQuestion=d.querySelector('[data-question-id="check-1"]');
    const normalImage=normalQuestion.querySelector(":scope > img");
    const expandedQuestion=d.querySelector('[data-question-id="check-2"]');
    const expandedImage=expandedQuestion.querySelector(":scope > img");
    check(Math.abs(normalImage.offsetWidth/normalQuestion.clientWidth-.82)<.03 && expandedImage.offsetWidth/expandedQuestion.clientWidth>.97,"Normal crops print compact while expanded crops stay full width");
    check(d.querySelectorAll(".paper-watermark").length===pages.length,"Watermark present on every page");
    check([...d.querySelectorAll(".paper-content")].every(content=>content.getBoundingClientRect().bottom<content.closest(".paper-page").querySelector("footer").getBoundingClientRect().top),"No content overlaps page footer");
    const before=[...d.querySelectorAll(".final-question")].map(q=>q.dataset.questionId).join();
    d.querySelector("#docGroupSelect").value="B";
    d.querySelector("#docGroupSelect").dispatchEvent(new w.Event("change"));
    await new Promise(resolve=>setTimeout(resolve,700));
    const after=[...d.querySelectorAll(".final-question")].map(q=>q.dataset.questionId).join();
    check(before!==after && s.questions[0].id==="check-0","Booklet B changes order without modifying workspace");
    const file=await w.createDocumentPdfFile();
    check(file.filename.endsWith("-B.pdf") && new TextDecoder().decode(file.pdfBytes.slice(0,5))==="%PDF-","PDF export creates a real named PDF");
    const originalPicker=w.showSaveFilePicker;
    const originalCreate=w.createDocumentPdfFile;
    const calls=[];
    let savedBytes=0;
    w.showSaveFilePicker=async()=>{calls.push("picker");return {createWritable:async()=>({write:async blob=>{savedBytes=blob.size;},close:async()=>{}})};};
    w.createDocumentPdfFile=async()=>{calls.push("pdf");return originalCreate();};
    await w.downloadDocumentPdf();
    check(calls.join(",")==="picker,pdf" && savedBytes===file.pdfBytes.length,"Save As opens before rendering and writes the complete PDF");
    calls.length=0;
    w.showSaveFilePicker=async()=>{throw new w.DOMException("Cancelled","AbortError");};
    await w.downloadDocumentPdf();
    check(calls.length===0,"Cancelling Save As does not create or download a file");
    w.showSaveFilePicker=originalPicker;
    w.createDocumentPdfFile=originalCreate;
    const pdf=await w.pdfjsLib.getDocument({data:file.pdfBytes.slice()}).promise;
    pages=[...d.querySelectorAll(".paper-page")];
    check(pdf.numPages===pages.length,"PDF and preview have identical page counts");
    const page=await pdf.getPage(1);
    const viewport=page.getViewport({scale:1});
    check(Math.abs(viewport.width/viewport.height-210/297)<.002,"Exported PDF uses actual A4 dimensions");
    const rendered=document.createElement("canvas");
    rendered.width=viewport.width;rendered.height=viewport.height;
    await page.render({canvasContext:rendered.getContext("2d"),viewport}).promise;
    document.querySelector("#pdfImage").src=rendered.toDataURL();
    const pixels=rendered.getContext("2d").getImageData(0,0,rendered.width,rendered.height).data;
    let ink=0;for(let i=0;i<pixels.length;i+=4)if(pixels[i]<230||pixels[i+1]<230||pixels[i+2]<230)ink++;
    check(ink>10000,"Exported PDF contains visible page content");
    w.closeModal(d.querySelector("#documentModal"));
    w.openSplitModal("check-2",2);
    check(!d.querySelector("#splitModal").classList.contains("hidden"),"Section split opens on a valid question");
    w.closeModal(d.querySelector("#splitModal"));
    check(s.questions[8] && w.getQuestionNumberMap().get(s.questions[8].id)==="1","Section numbering restarts at one");
    w.openWatermarkModal();
    d.querySelector('input[name="watermarkType"][value="image"]').checked=true;
    d.querySelector("#watermarkImagePreview").src=source;
    w.saveWatermark();
    check(s.settings.watermark.type==="image" && s.settings.watermark.image===source,"Image watermark is saved");
    s.settings.printOptions.preserveTitleCase=true;
    s.settings.printOptions.centerMeta=true;
    s.settings.printOptions.lineTextToggle=true;
    s.settings.printOptions.lineTextValue="Key Test";
    d.querySelector("#groupName").value="Grup Yok";
    d.querySelector("#paperSize").value="a5";
    d.querySelector("#orientation").value="landscape";
    await w.openDocumentPreview();
    pages=[...d.querySelectorAll(".paper-page")];
    check(Math.abs(pages[0].offsetWidth/pages[0].offsetHeight-210/148)<.005,"A5 landscape uses correct dimensions");
    check(d.querySelector(".final-title").textContent==="Turkce denemesi" && d.querySelector(".final-meta.centered") && d.querySelector("footer small").textContent==="Key Test","Other page settings affect output");
    check(d.querySelector(".paper-watermark img"),"Image watermark appears on paper");
    result.textContent=output.join("\n")+"\nALL CHECKS PASSED";
  } catch(error) {result.textContent=output.join("\n")+"\nERROR: "+error.stack;}
};
